### ISSUE TITLE
Please upload csv to geocoding folder and change csv file reference

### ISSUE THREAD

**Issue by puikwan** [DataKind-SG/effective_altruism#19]
file: Addresses2 API.ipynb
line:
data1=pd.read_csv("C:\Users\kaisyuenl\Data science projects\DataKind SG 13-15 April 2018\effective_altruism\eda\geocoding\KSaddresses2.csv")

**Comment by syuenloh** [comment]
Added addresses1, addresses2, addresses3, addresses4, addresses5  csvs into geocoding directory and changed csv file reference.
